spring.application.name=event-booking-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/eventbooking
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080
jwt.secret=this-is-a-very-long-secret-key-for-jwt-signing-change-in-production-min-32-chars
jwt.expiration-ms=86400000
logging.level.org.springframework.security=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379
seat-hold.ttl-seconds=300
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking_logs
